spring.application.name=tools
server.port = 6969
youtube.api.key=
youtube.api.base.url=https://www.google.com/youtube/v3
youtube.api.search.url=${youtube.api.base.url}/search
youtube.api.videos.url=${youtube.api.base.url}/videos

#max no of videos data
youtube.api.max.related.videos=3